### ISSUE TITLE
Reattaching imported functions

### ISSUE THREAD

**Issue by void4** [mohanson/pywasm#45]
I call a runtime instance several times, but each time I need to reattach env functions (because apparently, the old ones refer to outdated data). On first try

`runtime.imps = newimps`

does not seem to work. Is this possible? I'd prefer to do this without having to reload the entire runtime (which would necessitate loading the .wasm binary from the filessystem again etc.)

**Comment by mohanson** [comment]
You should directly modify the relevant elements in the store object, because WebAssembly has an initialization step, and the imps parameter will not be used after this step.

https://github.com/mohanson/pywasm/blob/master/pywasm/execution.py#L296

https://github.com/mohanson/pywasm/blob/master/pywasm/execution.py#L205

But I don't approve of this usage. You may be able to add a `reset()` function, or some other things, to solve it at the application layer.

**Comment by void4** [comment]
My problem is that the functions need to refer to some data in an object distance, which may be different for every invocation.

Because there may be many threads/interleaved invocations of several interpreters, I can't declare this instance to be global inside the function. I tried the nonlocal keyword, but it seems to refer to the old data anyway, it is apparently bound when the function is defined.
